apiVersion: apps/v1
kind: Deployment
metadata:
  name: billingmanagement-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: billing
  template:
    metadata:
      labels:
        component: billing
    spec:
      containers:
        - name: billingmanagement
          image: deven2690/billingmanagement
          ports:
            - containerPort: 8381
          env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-cluster-ip-service
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-cluster-ip-service/InventoryMgr
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING.JPA.DATABASE-PLATFORM
              value: org.hibernate.dialect.PostgreSQLDialect
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD