apiVersion: apps/v1
kind: Deployment
metadata:
  name: customermanagement-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: customer
  template:
    metadata:
      labels:
        component: customer
    spec:
      containers:
        - name: customermanagement
          image: deven2690/customermanagement
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-cluster-ip-service/InventoryMgr
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: JAVAX.PERSISTENCE.SCHEMA-GENERATION.DATABASE.ACTION
              value: create
            - name: SPRING.JPA.DATABASE-PLATFORM
              value: org.hibernate.dialect.PostgreSQLDialect
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD          